### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by pkrishn** [githubteacher/devs-may-2016#3]
Learn more about github

**Comment by pkrishn** [comment]
test

**Comment by brianamarie** [comment]
Hello @pkrishn :wave: 

To be added as a collaborator, go to [this issue](https://github.com/githubteacher/devs-may-2016/issues/2) and comment. :smile:

**Comment by githubteacher** [comment]
:tada: @pkrishn is now a repository collaborator. :balloon:
