### ISSUE TITLE
dfstestmatt's recommendations in Chicago

### ISSUE THREAD

**Issue by dfstestmatt** [githubteacher/devs-may-2016#9]
## Matt's Recommendation

I'd like to see a chat/messenger app within GitHub :smiley:

**Comment by brianamarie** [comment]
@dfstestmatt If/when it gets whitelisted, we might try an integration that we use with our webinars, gitter.im. :smile:

**Comment by brianamarie** [comment]
You can find more official info [here](https://github.com/integrations/gitter).

**Comment by dfstestmatt** [comment]
Awesome, thanks!!!

**Comment by brianamarie** [comment]
After you've logged into the proxy, try: `git clone https://github.com/githubteacher/devs-may-2016`
